# QF627 Pre-Course Workshop | Introduction to Programming

## Lesson 2 | An Introduction to `NumPy` | view

> In the previous lesson, you have learned about `methods and functions` that are available in built-in Python, along with variables and data types.

> First, let us begin with some basic built-in Python that you need to fully understand before we proceed.

> Here's a quick reminder regarding the useful hotkeys for scripting on Jupyter Notebook :)

- `a` inserts a cell above 
- `b` inserts a cell below
- `dd` (double d) deletes a cell 
- `esc` jumps out of the cell
- `return/enter` gets into the cell
- `m` makes your cell markdown
- `y` makes your cell codeL
- `shift + control + -` splits the cell
- `shift + m` merges the cells
- `shift + l` adds line numbers into the cell

> Now you will start learning about how to use `packages`.

> As Python is open-source language, using the humongous ecosystem of packages will help you work more efficiently.

> A `package is a collection of Python modules and scripts` giving you new data types, functions, and methods.


### How to `install` a ***package***?

> To use a package, you need to download it first.

> Let's use the command `pip3 install target_package` so that you can install packages of your interest.

> For downloading a package, you need to do this just once, yet you should import in your workspace whenever you wish to use it.

> The command below will load the NumPy package into Python for your use.

In [1]:
!pip install numpy

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple


In [2]:
import numpy as np

***Wait, why do we use alias here (i.e., as `np`)? ?*** 

> As you will see below, 

- To access the array() function, you need to use np.array() to indicate that the function is from the NumPy package.

> Yes, the reason why we have used np as alias is to minimize our typing task.

### The Basics

> Using `NumPy`, you can create a new data type called `array`.

> Why use data type `array`?

**`array` is useful for financial analysis because...**

- array `stores` data more efficiently

- array `performs` faster than built-in Python lists in terms of computations (access in reading and writing items faster as the package is optimized for numerical analyses)

- array `shows` better performance with relatively larger datasets

- array, most importantly, **`enables` you to utilize `array-related functions`**--you can perform statistical modelling and visualization easier, which is critical for financial analysis.





> **A good way to understand about the usefulness of NumPy is to compare array with list (yes, that list that you learned in the previous lesson).**

#### Differences 1. Arrays can contain only a single data type (unlike lists).

In [3]:
our_list = ["Year", 2021, True]
print(our_list)

['Year', 2021, True]


In [4]:
type(our_list)

list

> As you will see below, arrays in NumPy will convert the elements in the list to the most compatible data types.

In [5]:
our_array = np.array(["Year", 2021, True])
print(our_array)

['Year' '2021' 'True']


In [6]:
type(our_array) # n-dimensional array

numpy.ndarray

In [7]:
# Here are lists.
earnings_list = [10.09, 10.28, 2.21, 6.19, 8.24]
prices_list = [99.98, 87.68, 154.23, 162.12, 121.11]

> How would you make objects `earnings` and `prices` arrays?

In [8]:
earnings_array = np.array(earnings_list)
prices_array = np.array(prices_list)

In [9]:
print(earnings_array);print(earnings_list)

[10.09 10.28  2.21  6.19  8.24]
[10.09, 10.28, 2.21, 6.19, 8.24]


#### Differences 2. Arrays have different ways of operations (than lists).

> Let's see how lists behave first.

In [10]:
pe_ratio_list = prices_list + earnings_list
print(pe_ratio_list)

[99.98, 87.68, 154.23, 162.12, 121.11, 10.09, 10.28, 2.21, 6.19, 8.24]


In [11]:
output = []

In [12]:
for first, second in zip(prices_list, earnings_list):
    output.append(first + second)

In [13]:
output

[110.07000000000001, 97.96000000000001, 156.44, 168.31, 129.35]

> The two objects were merely concatenated. It's just extended. That's not what we want...

In [14]:
pe_ratio_array = prices_array + earnings_array
print(pe_ratio_array)

[110.07  97.96 156.44 168.31 129.35]


In [15]:
prices_array != earnings_array

array([ True,  True,  True,  True,  True])

> ***Arrays allow for efficient numerical manipulation of its elements.***

> Let's calculate `the dollar amount an investor can expect to invest in a company to receive one dollar of that company’s earnings`--yes, the `price to earnings ratio`--using two arrays, earnings_array and prices_array above.

In [16]:
pe_ratio_array = prices_array / earnings_array

print(pe_ratio_array)

[ 9.90882061  8.52918288 69.78733032 26.19063005 14.69781553]


> You could see here that arrays perform `element-wise mathematical operations`.

#### Indexing, Subsetting, Filtering, & Slicing: Similarities between `array` and `list`

> We have seen differences between arrays and lists.

> Here are also similarities.

In [17]:
subset_earnings_array = earnings_array[1:3]
print(subset_earnings_array)

[10.28  2.21]


In [18]:
another_subset_earnings_array = earnings_array[-3: ]
print(another_subset_earnings_array)

[2.21 6.19 8.24]


In [19]:
every_other_element_earnings_array = earnings_array[0:5:2]
print(every_other_element_earnings_array)

[10.09  2.21  8.24]


> Please address the error message above.

### Arrays in NumPy can be `multi`dimensional.

![](ndim.png)
#### How to add image (CLICK HERE TWICE)

> A common form of financial data comes with a rectangular form of data that contains rows and columns. 

> Such data can be represented with two-dimensional arrays.

> To create a two-dimensional array using NumPy, you can use the same function array().

> Instead of providing a single list as your input, let's pass in a list of two lists as your input.

> Here, let's pass earnings and prices to create a two-dimensional array.

In [20]:
nested_list = [[10.09, 10.28, 2.21, 6.19, 8.24],[99.98, 87.68, 154.23, 162.12, 121.11]]
print(nested_list)

[[10.09, 10.28, 2.21, 6.19, 8.24], [99.98, 87.68, 154.23, 162.12, 121.11]]


In [21]:
pe_array = np.array([[10.09, 10.28, 2.21, 6.19, 8.24],[99.98, 87.68, 154.23, 162.12, 121.11]])
print(pe_array)

# Recall that there were two lists of earnings_list and prices_list


[[ 10.09  10.28   2.21   6.19   8.24]
 [ 99.98  87.68 154.23 162.12 121.11]]


In [22]:
pe_array_twins = np.array([earnings_list, prices_list])
print(pe_array_twins)

[[ 10.09  10.28   2.21   6.19   8.24]
 [ 99.98  87.68 154.23 162.12 121.11]]


In [23]:
pe_array == pe_array_twins

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

> You might want to use `boolean` arrays as well. 

> As you will see below, Boolean arrays are quite useful for subsetting--stay tuned :)

#### Methods in Array

> Like list, array also has many useful methods.

In [24]:
dir(pe_array_twins)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [25]:
help(pe_array_twins.shape)

Help on tuple object:

class tuple(object)
 |  tuple(iterable=(), /)
 |  
 |  Built-in immutable sequence.
 |  
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |  
 |  If the argument is a tuple, the return value is the same object.
 |  
 |  Built-in subclasses:
 |      asyncgen_hooks
 |      UnraisableHookArgs
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iter__(self, /)
 |

##### array.shape

In [26]:
np.shape(pe_array)

(2, 5)

##### array.size

In [27]:
np.size(pe_array) # 2 * 5

10

##### array.transpose

In [28]:
print(pe_array)

[[ 10.09  10.28   2.21   6.19   8.24]
 [ 99.98  87.68 154.23 162.12 121.11]]


In [29]:
transposed_pe_array = np.transpose(pe_array)
print(transposed_pe_array)

[[ 10.09  99.98]
 [ 10.28  87.68]
 [  2.21 154.23]
 [  6.19 162.12]
 [  8.24 121.11]]


### Subsetting

> Remember how to subset nested lists? Subsetting two-dimensional arrays is similar to subsetting nested lists. 

> In a 2D array, the indexing/slicing should be specific to the dimension of the array: **`array[row, column]`**

##### How would you subset `earnings` from the `transposed pe_array`? 

In [30]:
earnings = transposed_pe_array[ : , 0]
print(earnings)

[10.09 10.28  2.21  6.19  8.24]


##### How would you subset `prices` from the `transposed pe_array`? 

In [31]:
prices = transposed_pe_array[ : , -1]
print(prices)

[ 99.98  87.68 154.23 162.12 121.11]


In [32]:
transposed_pe_array[ : , 1] == pe_array[ 1 , : ]

array([ True,  True,  True,  True,  True])

In [33]:
print(transposed_pe_array)

[[ 10.09  99.98]
 [ 10.28  87.68]
 [  2.21 154.23]
 [  6.19 162.12]
 [  8.24 121.11]]


##### How would you subset the `earnings and prices for third and forth companies` from the `transposed pe_array`?

In [34]:
pe_34 = transposed_pe_array[2:4, : ]
print(pe_34)

[[  2.21 154.23]
 [  6.19 162.12]]


In [35]:
transposed_pe_array[2:4, : ] == pe_array[ : , 2:4 ]

array([[ True, False],
       [False,  True]])

In [36]:
print(pe_array); print(transposed_pe_array)

[[ 10.09  10.28   2.21   6.19   8.24]
 [ 99.98  87.68 154.23 162.12 121.11]]
[[ 10.09  99.98]
 [ 10.28  87.68]
 [  2.21 154.23]
 [  6.19 162.12]
 [  8.24 121.11]]


> ***Review & Expansion of Your Vocabulary: Below are some useful basics for array.***

In [37]:
# Get Dimension
transposed_pe_array.ndim == 2

True

In [38]:
# Get Shape
transposed_pe_array.shape

(5, 2)

In [39]:
# Get Type 19:41???
transposed_pe_array.dtype

dtype('float64')

In [40]:
# Get Size
transposed_pe_array.itemsize

8

In [41]:
# Get total size , 查字节
transposed_pe_array.nbytes

80

In [42]:
# Get number of elements
transposed_pe_array.size

10

In [43]:
# Get a specific element [row, column]
transposed_pe_array[0, 0]

10.09

In [44]:
# Get a specific row 
transposed_pe_array[-1, : ]

array([  8.24, 121.11])

In [45]:
# Get a specific column
transposed_pe_array[ : , 1]

array([ 99.98,  87.68, 154.23, 162.12, 121.11])

In [46]:
# Getting a little more fancy [startindex:endindex:stepsize]
transposed_pe_array[0:4:2, 1 ]

array([ 99.98, 154.23])

In [47]:
transposed_pe_array

array([[ 10.09,  99.98],
       [ 10.28,  87.68],
       [  2.21, 154.23],
       [  6.19, 162.12],
       [  8.24, 121.11]])

#### `WARNING`: Please be careful when `copying arrays`!

In [48]:
l = np.array([100, 200, 300])
m = l
m[0] = 400
print(m)

[400 200 300]


In [49]:
print(l) # L居然也会跟着变！

[400 200 300]


In [50]:
n = np.array([500, 600, 700])
o = n.copy() # .copy is so important!
o[1] = 800
print(o)
print(n)

[500 800 700]
[500 600 700]


### Mathematics with NumPy

> **`We all love mathematics`. For a lot more**, [check this out](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

- For example, `linear algebra`, look at [here](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html).

#### Statistics

> Not only can you perform element-wise calculations on NumPy arrays, you can also calculate summary statistics such as range, mean, and standard deviation of arrays using functions from NumPy.

##### Calculating the range (minimum and maximum values)

In [51]:
print(pe_array)

[[ 10.09  10.28   2.21   6.19   8.24]
 [ 99.98  87.68 154.23 162.12 121.11]]


In [52]:
np.min(pe_array)

2.21

In [53]:
np.max(pe_array)

162.12

In [54]:
np.max(pe_array, axis = 0)

array([ 99.98,  87.68, 154.23, 162.12, 121.11])

In [55]:
np.sum(pe_array)

662.13

In [56]:
np.sum(pe_array, axis = 1)

array([ 37.01, 625.12])

##### Calculating the mean (`mean`) and standard deviation (`std`)

In [57]:
earnings_mean = np.mean(earnings_array)
print(earnings_mean)

7.401999999999999


In [58]:
print(pe_array)

[[ 10.09  10.28   2.21   6.19   8.24]
 [ 99.98  87.68 154.23 162.12 121.11]]


In [59]:
earnings_mean_twins = np.mean(pe_array[0,:])
earnings_mean_twins == earnings_mean

True

In [60]:
prices_std = np.std(prices_array)
print(prices_std)

29.210269837849836


In [61]:
prices_std_twins = np.std(pe_array[1,:])
prices_std_twins == prices_std

True

##### Generating a sequence of numbers

> Often you may want to create an array of a range of numbers (e.g., 1 to 500) without having to type in every single number. 

> The NumPy function `arange()` is an efficient way to create numeric arrays of a range of numbers--using arange() can be much faster than typing each individual element.

> The arguments for `arange()` include the `start`, `stop`, and `step interval` as follows: `np.arange(start, stop, step)`


In [3]:
ticker_ids = np.arange(1, 1001, 1)
print(ticker_ids)

[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25   26   27   28
   29   30   31   32   33   34   35   36   37   38   39   40   41   42
   43   44   45   46   47   48   49   50   51   52   53   54   55   56
   57   58   59   60   61   62   63   64   65   66   67   68   69   70
   71   72   73   74   75   76   77   78   79   80   81   82   83   84
   85   86   87   88   89   90   91   92   93   94   95   96   97   98
   99  100  101  102  103  104  105  106  107  108  109  110  111  112
  113  114  115  116  117  118  119  120  121  122  123  124  125  126
  127  128  129  130  131  132  133  134  135  136  137  138  139  140
  141  142  143  144  145  146  147  148  149  150  151  152  153  154
  155  156  157  158  159  160  161  162  163  164  165  166  167  168
  169  170  171  172  173  174  175  176  177  178  179  180  181  182
  183  184  185  186  187  188  189  190  191  192  193  194  195  196
  197 

> How would you create `odd numbers only`?

In [63]:
ticker_ids_odd = np.arange(1, 1001, 2)
print(ticker_ids_odd)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
 433 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467
 469 471 473 475 477 479 481 483 485 487 489 491 49

> How would you create **`even`** numbers only then? 

In [64]:
ticker_ids_even = ticker_ids_odd + 1
print(ticker_ids_even)

[   2    4    6    8   10   12   14   16   18   20   22   24   26   28
   30   32   34   36   38   40   42   44   46   48   50   52   54   56
   58   60   62   64   66   68   70   72   74   76   78   80   82   84
   86   88   90   92   94   96   98  100  102  104  106  108  110  112
  114  116  118  120  122  124  126  128  130  132  134  136  138  140
  142  144  146  148  150  152  154  156  158  160  162  164  166  168
  170  172  174  176  178  180  182  184  186  188  190  192  194  196
  198  200  202  204  206  208  210  212  214  216  218  220  222  224
  226  228  230  232  234  236  238  240  242  244  246  248  250  252
  254  256  258  260  262  264  266  268  270  272  274  276  278  280
  282  284  286  288  290  292  294  296  298  300  302  304  306  308
  310  312  314  316  318  320  322  324  326  328  330  332  334  336
  338  340  342  344  346  348  350  352  354  356  358  360  362  364
  366  368  370  372  374  376  378  380  382  384  386  388  390  392
  394 

#### Boolean arrays can be a very powerful way to subset arrays. 

> As a case in point, let's try to identify the earnings that are greater than average from a list of earnings.

> To do so, let's find the mean value of earnings first.

In [65]:
mean_earnings = np.mean(earnings_array)

##### How would you index earnings that are lesser than average

> Hint: You might want to create a boolean array first.

In [66]:
boolean_array = (earnings_array < mean_earnings)
print(boolean_array)

[False False  True  True False]


In [67]:
earnings[boolean_array] == earnings[earnings_array < mean_earnings]

array([ True,  True])

In [68]:
earings_below_mean = earnings[boolean_array] # 厉害！
print(earings_below_mean)

[2.21 6.19]


> Boolean array can be used for strings as well. 

> Let's create the names of companies with their associated industry first. 

> Here, your want to find all companies that are categorized as `Investment Services` industry.

In [69]:
array_for_companies = np.array(["Facebook", "Amazon", "Netflix", "Google",
                               "Citigroup", "Goldman Sachs", "Tesla", "Microsoft"])

In [70]:
array_for_industries = np.array(["Tech", "Tech", "Tech", "Tech",
                               "Investment Services", "Investment Services", "Data", "Tech"])

In [71]:
array_for_companies_industries = np.array([array_for_companies,
                                           array_for_industries])
print(array_for_companies_industries)

[['Facebook' 'Amazon' 'Netflix' 'Google' 'Citigroup' 'Goldman Sachs'
  'Tesla' 'Microsoft']
 ['Tech' 'Tech' 'Tech' 'Tech' 'Investment Services' 'Investment Services'
  'Data' 'Tech']]


##### How would you subset Investment Services industry and print companies in Investment Servecies?

In [72]:
bools_array = (array_for_industries == "Investment Services")
print(bools_array)

[False False False False  True  True False False]


In [73]:
investment_services = array_for_companies[bools_array]
print(investment_services)

['Citigroup' 'Goldman Sachs']


### Installation of 'numpy-financial'

In [74]:
!pip install numpy-financial

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple


In [13]:
import numpy_financial as npf

In [76]:
npf.__path__

['D:\\360Downloads\\anaconda-2021.08\\lib\\site-packages\\numpy_financial']

In [77]:
import sys

In [78]:
sys.path

['C:\\Users\\13209\\Desktop\\QF627',
 'D:\\360Downloads\\anaconda-2021.08\\python38.zip',
 'D:\\360Downloads\\anaconda-2021.08\\DLLs',
 'D:\\360Downloads\\anaconda-2021.08\\lib',
 'D:\\360Downloads\\anaconda-2021.08',
 '',
 'D:\\360Downloads\\anaconda-2021.08\\lib\\site-packages',
 'D:\\360Downloads\\anaconda-2021.08\\lib\\site-packages\\locket-0.2.1-py3.8.egg',
 'D:\\360Downloads\\anaconda-2021.08\\lib\\site-packages\\win32',
 'D:\\360Downloads\\anaconda-2021.08\\lib\\site-packages\\win32\\lib',
 'D:\\360Downloads\\anaconda-2021.08\\lib\\site-packages\\Pythonwin',
 'D:\\360Downloads\\anaconda-2021.08\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\13209\\.ipython']

> For your information, there is `numpy_financial` package that contains a collection of elementary financial functions. 

> It will make your life easier when working with financial values.

> For example, the function .pv(rate, nper, pmt, fv) allows you to calculate the present value of an investment with some parameters:

- `rate` The rate of return of the investment
- `nper` The lifespan of the investment
- `pmt` The (fixed) payment at the beginning or end of each period
- `fv` The future value of the investment

> You can use this formula in many ways (e.g., you can calculate the present value of future investments in today's dollars).

> Before you run the code above, you should have installed the package `numpy-financial`.

In [79]:
your_investment = npf.pv(rate = 0.07, nper = 10, pmt = 0, fv = 30000) # present value

> Here, the present value returned is negative, so we multiply the result by -1

In [80]:
print("Your investment is worth " + str(round(-your_investment,2)) + " in today's dollars.")

Your investment is worth 15250.48 in today's dollars.


In [81]:
your_sister_investment = npf.pv(rate = 0.06, nper = 40, pmt = 0, fv = 24000)
print("Your sisiter's investment is worth " + str(round(-your_sister_investment,2)) + " in today's dollars.")

Your sisiter's investment is worth 2333.33 in today's dollars.


> Similarly, you can also calculate the future value of an investment the following parameters:

- `rate` The rate of return of the investment
- `nper` The lifespan of the investment
- `pmt` The (fixed) payment at the beginning or end of each period (which is 0 in our example)
- `pv` The present value of the investment

> Here, you can use the function .fv(rate, nper, pmt, pv).

> Note that you should `input a negative value into the pv parameter` if it represents `a negative cash flow (cash going out)`. 

> That is, if you were to compute the future value of an investment, requiring an up-front cash payment, you would need to `input a negative value to the pv parameter` in the function .fv().

# Estimate Your Investment's Future Value

In [82]:
your_investment_fv = npf.fv(rate = 0.045, nper = 15, pmt = 0, pv = -24000)
print("Your investment will return a total of $" + str(round(your_investment_fv)) + " in 15 years.")

Your investment will return a total of $46447 in 15 years.


# Estimate the Future Value of Your Friend's Investment

In [7]:
your_friend_investment_fv = npf.fv(rate = 0.06, nper = 27, pmt = -10000, pv = -30000)
print("Your friend's investment will return a total of $" + str(round(your_friend_investment_fv)) + " in 27 years.")

Your friend's investment will return a total of $781728 in 27 years.


In [9]:
yearly = 0
help(npf.pmt())

TypeError: pmt() missing 3 required positional arguments: 'rate', 'nper', and 'pv'

In [40]:
money_of_endwork = npf.pv(rate = 0.08, nper = 50, pmt = -1200000, fv = 0)
print(money_of_endwork)
yearly_saving = npf.pmt(rate = 0.08, nper = 18, pv = -150000, fv = money_of_endwork)
print(yearly_saving)

14680181.57167265
-375986.30184150883


##### Now let's adjust future values of your investment for inflation with the following steps:

**1. forecast the future value of an investment given a rate of return**

**2. discount the future value of the investment by a projected inflation rate**

> Here, we will `utilize both functions .fv() and .pv()` to estimate the projected value of a given investment in today's dollars, adjusted for inflation.

> ***Scenario***: `Investment returning 7% per year for 25 years`

In [84]:
your_father_investment_fv = npf.fv(rate = 0.07, nper = 25, pmt = 0, pv = -20000)
print("Your father's investment will return a total of $" + str(round(your_father_investment_fv)) + " in 25 years.")

Your father's investment will return a total of $108549 in 25 years.


> ***Scenario***: `Inflation rate of 2.5% per year for 25 years`

In [85]:
discounted_your_father_investment = npf.pv(rate = 0.025, nper = 25, pmt = 0, fv = your_father_investment_fv)
print("After adjusting for inflation, your father's investment is worth $" + str(round(-discounted_your_father_investment)) + " in today's dollars.")

After adjusting for inflation, your father's investment is worth $58550 in today's dollars.


> `Thank you for working with the script :)`

In [86]:
exit()